### ISSUE TITLE
linuxconsole git commit ref doesn't exist in upstream

### ISSUE THREAD

**Issue by legooolas** [m42uko/linux-fsia6b#1]
The commit ref the submodule refers to doesn't appear in the upstream repo, so the submodule commands don't work!

Getting the current HEAD doesn't allow the patch to apply cleanly, but it's a simple fix (the --fsia6b option entry patch context doesn't match with the current code) so I just edited it in for now, so it may be worth updating both the submodule and patch to work with the latest commit?  :)
Everything then works as expected  :+1:

**Comment by m42uko** [comment]
Thanks for letting me know! I have no idea why that commit disappeared...

Do you want to provide your fix via a pull request (so that you get credited) or should I just update it myself?

**Comment by legooolas** [comment]
I'll make a patch and will return shortly  :)

**Comment by m42uko** [comment]
Merged. Thanks :)
